### ISSUE TITLE
getAutomationType() throws nullPointerException

### ISSUE THREAD

**Issue by IvoDimitrov** [dtopuzov/mobile-testing#5]
When automationName is not added to config file getAutomationType() throws nullPointerException.
**Current version:**
private String getAutomationType() throws Exception {
        String automation = this.properties.getProperty("automationName", null)**_.toLowerCase()_**;
        if (automation != null) {
            return automation;
        } else {
}

**Solution:**
private String getAutomationType() throws Exception {
        String automation = this.properties.getProperty("automationName", null);
        if (automation != null) {
            return automation.**_toLowerCase()_**;
        } else {
}

**Comment by dtopuzov** [comment]
Resolved in master.
